services:
  recommender:
    build: .
    ports:
      - '8000:8000'
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5431
      DB_NAME: mangaka_db
      DB_USER: postgres
      DB_PASS: 123456
